config/routes.rb
Indigo::Application.routes.draw do
  get "omniauth_callbacks/vkontakte"
  get "users/controller"
  resources :posts do
    resources :comments do
      member do
        post :vote_up
        post :vote_down
      end
    end
  end

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  resources :users, :only => [:index, :destroy]
  root :to => 'users#index'

  resources :tags, :only => [:show]
  
  

  

end

app/models/post.rb
class Post < ActiveRecord::Base

	has_many :comments, dependent: :destroy
	validates :title, presence: true, 
	                  length: { minimum: 3 }
	validates :content, presence: true
	
	acts_as_taggable
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  load_and_authorize_resource
	def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    if @post.save
      redirect_to @post
    else
      render 'new'
    end
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    if @post.update(post_params)
      redirect_to @post
    else
      render 'edit'
    end
  end

  def show
    @post = Post.find(params[:id])
    #@topcomment = Comment.find
  end 

  def index
    @posts = Post.paginate(:order => "created_at DESC", :page => params[:page], :per_page => 2)
  end


  private
    def post_params
      params.require(:post).permit(:title, :content, :tag_list)
    end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<%= form_for @post do |f| %>
  <% if @post.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@post.errors.count, "error") %> prohibited
        this post from being saved:</h2>
    <ul>
    <% @post.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
  <% end %>
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title, class: 'form-control' %>
  </p>
 
  <p>
    <%= f.label :image %><br>
    <%= f.text_field :content, class: 'form-control' %>
  </p>
 
  <p>
    <%= f.label :tags %>, separated by comma<br>
    <%= f.text_field :tag_list, class: 'form-control' %>
  </p>

  <p>
    <%= f.submit "New post", class: 'btn btn-default' %>
  </p>
<% end %>

app/views/posts/_image.html.erb
<div class = "commentator">
	<div class = "image">
	 	<%= image_tag @post.content %>
	</div>
	<div class = "topcomment">
		<%- if @post.comments.any? %>
 		<h1>
 			<%= @post.comments.order(rating: :desc).first.body %>
 		</h1>
 		<h2>
 			- <%= link_to @post.comments.order(rating: :desc).first.user.username, user_path(@post.comments.order(rating: :desc).first.user) %>
 		</h2>
 		<%- else %>
 		<h1>
 			No comments!
 		</h1>
 		<% end %>
 		<%- if @post.tag_list %>
 		<div class = "tags">
 			<%- @post.tag_list.each do |tag| %>
 			<%= link_to "#" + "#{ tag }" %>
 			<% end %>
 		</div>
 		<% end %>
 		<%- if @post.comments.any? %>
 		<div class = "vote">
	       <%= link_to('-1', vote_down_post_comment_path(@post, @post.comments.order(rating: :desc).first), :method => :post) %> / 
	       <%= link_to('+1', vote_up_post_comment_path(@post, @post.comments.order(rating: :desc).first), :method => :post) %>
	       Total: <%= @post.comments.order(rating: :desc).first.rating %>
 		</div>
 		<% end %>
 	</div>
</div>

app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render 'form' %>
 
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<h1>Recent commentators</h1>
<table class="table">
	<%- @posts.each do |post| %>
	<div class = "one_post">
		<div class = "comments_counter">
			<%= link_to post.comments_count, post_path(post) %>
		</div>
	    <div class = "commentator">
	    	<div class = "img_header">
	    		<h2>
	    			<%= link_to post.title, post_path(post) %> | 
	    			<%- if can? :update, post %>
		    			<%= link_to 'Edit', edit_post_path(post) %>
						<%= link_to 'Delete', post_path(post),
				                method: :delete, data: { confirm: 'Are you sure?' } %>
				    <% end %>s
			    </h2>
			    <div class ="share"><%= image_tag 'http://cityofwaterfalls.ca/wp-content/plugins/wp-rss-multi-importer/images/facebook.png' %></div>
	    	</div>
	    	<div class = "image">
			 	<%= link_to image_tag("#{ post.content }"), post_path(post) %>
			</div>
			<div class = "topcomment">
				<%- if post.comments.any? %>
			 		<h1>
			 			<%= post.comments.order(rating: :desc).first.body %>
			 		</h1>
			 		<h2>
			 			- <%= link_to post.comments.order(rating: :desc).first.user.username, user_path(post.comments.order(rating: :desc).first.user) %>
			 		</h2>
		 		<%- else %>
			 		<h1>
			 			No comments!
			 		</h1>
		 		<% end %>
		 		<%- if post.tag_list %>
			 		<div class = "tags">
			 			<%- post.tag_list.each do |tag| %>
			 			<%= link_to "##{ tag }", tag_path(tag) %>
			 			<% end %>
			 		</div>
		 		<% end %>
		 		<%- if post.comments.any? %>
			 		<div class = "vote">
						<%= link_to('-1', vote_down_post_comment_path(post, post.comments.order(rating: :desc).first), :method => :post) %> / 
		      			<%= link_to('+1', vote_up_post_comment_path(post, post.comments.order(rating: :desc).first), :method => :post) %>
		       			Total: <%= post.comments.order(rating: :desc).first.rating %>
			 		</div>
		 		<% end %>
		 	</div>
		</div>
	</div>
	<% end %>
	<%= will_paginate @posts %>
</table>

app/views/posts/new.html.erb
<h1>New post</h1>

<%= render 'form' %>
 
<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p>
  <h1><%= @post.title %></h1>
</p>

<%= render 'image' %>

<div class = "comments">
  <h2>Comments:</h2>
  <% @post.comments.each do |comment| %>
    <p>
      <strong><%= link_to comment.user.username, user_path(comment.user) %></strong> said:
    </p>
  <div class="comment_body">
    <span><%= comment.body %></span>
    <div class = "comments_votes">
       <%= link_to('-1', vote_down_post_comment_path(@post, comment), :method => :post) %> / 
       <%= link_to('+1', vote_up_post_comment_path(@post, comment), :method => :post) %>
       Total: <%= comment.rating %>
    </div>
  </div>
<% end %>
  <h2>Add a comment:</h2>
  <%= form_for([@post, @post.comments.build]) do |f| %>
    <p>
      <%= f.hidden_field :post_id %>
    	<%= f.label :commenter %><br>
    	<%= f.text_field :commenter, class: 'form-control' %>
    </p>
    <p>
      <%= f.label :body %><br>
      <%= f.text_area :body, class: 'form-control' %>
    </p>
    <p>
    	<%= f.submit 'Submit', class: 'btn btn-default' %>
    </p>
  <% end %>
</div>
<%= link_to "Back", posts_path %>
| <%= link_to 'Edit', edit_post_path(@post) %>